pipeline:

    npm:install:
        image: node
        commands:
            - npm install --silent --progress=false
            - npm run install:theme

    npm:build:
        image: node
        commands:
            - npm run build

    docker:
        image: plugins/docker
        repo: sierrasoftworks/blog
        tag:
            - latest
            - "${DRONE_COMMIT_BRANCH}"
        username: "${DOCKER_USERNAME}"
        password: "${DOCKER_PASSWORD}"
        email: "${DOCKER_EMAIL}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"
