baseurl = "/"
languageCode = "en-GB"
title = "Sierra Softworks"

sectionPagesMenu = "menu"
paginate = 20

disqusShortname = "sierrasoftworks"
googleAnalytics = "UA-40095482-1"

theme = "minimalist"

themesDir = "themes"

pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
    site_author = "Benjamin Pannell"
    site_description = "The official Sierra Softworks blog"
    location = "Dublin, Ireland"
    avatar = "https://cv.sierrasoftworks.com/resources/avatar.jpg"
    logo = "https://cdn.sierrasoftworks.com/logos/icon.png"
    subtitle = "Blog"
    copyright = "Copyright Sierra Softworks"
    occupation = "Site Reliability Engineer, Microsoft"

    custom_css = ["/css/custom.css"]
    custom_js  = [
        "https://js.sentry-cdn.com/9b2237ebb25e438bb6bf3b819c419495.min.js"
    ]

    google_analytics = "UA-40095482-1"
    

[social]
    twitter   = "SierraSoftworks"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = "notheotherben"
    github    = "SierraSoftworks"
    gplus     = ""

[permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "GitHub"
    title = "View my open source GitHub projects"
    url = "https://github.com/SierraSoftworks"
    weight = 200
    pre = "<i class='icon-github'></i>"