name: Build Docker Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: sierrasoftworks/blog

jobs:
  push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registries
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Calculate version number
        id: version
        run: |
          VERSION=$(git describe --tags 2>/dev/null || git rev-parse --short HEAD)
          echo "::set-output name=version::$VERSION"

      - name: Push image to GitHub
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
          docker tag image $IMAGE_ID:${{ steps.version.outputs.version }}
          docker push $IMAGE_ID:${{ steps.version.outputs.version }}
