name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.12
    
    - name: Build Website (Staging)
      run: hugo --buildDrafts --buildFuture --destination ./out/staging

    - name: Upload Artifact for Website (Staging)
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: site-staging
        # A file, directory or wildcard pattern that describes what to upload
        path: ./out/staging
    
    - name: Build Website (Live)
      run: hugo --buildDrafts --buildFuture --destination ./out/live

    - name: Upload Artifact for Website (Live)
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: site-live
        # A file, directory or wildcard pattern that describes what to upload
        path: ./out/live

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Download Artifacts for Website (Staging)
        uses: actions/download-artifact@v2
        with:
          name: site-staging
          path: ./out
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Copy Artifacts to Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob sync --container $web --account-name blogsierrasoftworksbeta --source ./out
            az cdn endpoint purge -g app-blog -n blog-sierrasoftworks-staging --profile-name blog-sierrasoftworks --content-paths '/*'
  
  deploy-live:
    runs-on: ubuntu-latest
    needs: [build, deploy-staging]
    if: github.event_name == 'push'
    
    steps:
      - name: Download Artifacts for Website (Live)
        uses: actions/download-artifact@v2
        with:
          name: site-live
          path: ./out
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Copy Artifacts to Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob sync --container $web --account-name blogsierrasoftworks --source ./out
            az cdn endpoint purge -g app-blog -n blog-sierrasoftworks-live --profile-name blog-sierrasoftworks --content-paths '/*'
