name: Publish Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  STAGING_STORAGE_CONTAINER: "$web"
  STAGING_STORAGE_ACCOUNT: "blogsierrasoftworksbeta"
  STAGING_CDN_RESOURCEGROUP: app-blog
  STAGING_CDN_PROFILE: "blog-sierrasoftworks"
  STAGING_CDN_ENDPOINT: "blog-sierrasoftworks-staging"

  LIVE_STORAGE_CONTAINER: "$web"
  LIVE_STORAGE_ACCOUNT: "blogsierrasoftworks"
  LIVE_CDN_RESOURCEGROUP: app-blog
  LIVE_CDN_PROFILE: "blog-sierrasoftworks"
  LIVE_CDN_ENDPOINT: "blog-sierrasoftworks-live"
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.12
    
    - name: Build Website (Staging)
      run: hugo --buildDrafts --buildFuture --destination ./out/staging

    - name: Upload Artifact for Website (Staging)
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: site-staging
        # A file, directory or wildcard pattern that describes what to upload
        path: ./out/staging
    
    - name: Build Website (Live)
      run: hugo --buildDrafts --buildFuture --destination ./out/live

    - name: Upload Artifact for Website (Live)
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: site-live
        # A file, directory or wildcard pattern that describes what to upload
        path: ./out/live

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Download Artifacts for Website (Staging)
        uses: actions/download-artifact@v2
        with:
          name: site-staging
          path: ./out
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Copy Artifacts to Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Uploading Site Contents"
            az storage blob sync --container '${{ env.STAGING_STORAGE_CONTAINER }}' --account-name ${{ env.STAGING_STORAGE_ACCOUNT }} --source ./out

      - name: Purge Azure CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Purging CDN"
            az cdn endpoint purge -g ${{ env.STAGING_CDN_RESOURCEGROUP }} -n ${{ env.STAGING_CDN_ENDPOINT }} --profile-name ${{ env.STAGING_CDN_PROFILE }} --content-paths '/*'
  
  deploy-live:
    runs-on: ubuntu-latest
    needs: [build, deploy-staging]
    if: github.event_name == 'push'
    
    steps:
      - name: Download Artifacts for Website (Live)
        uses: actions/download-artifact@v2
        with:
          name: site-live
          path: ./out
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Copy Artifacts to Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Uploading Site Contents"
            az storage blob sync --container '${{ env.LIVE_STORAGE_CONTAINER }}' --account-name ${{ env.LIVE_STORAGE_ACCOUNT }} --source ./out

      - name: Purge Azure CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Purging CDN"
            az cdn endpoint purge -g ${{ env.LIVE_CDN_RESOURCEGROUP }} -n ${{ env.LIVE_CDN_ENDPOINT }} --profile-name ${{ env.LIVE_CDN_PROFILE }} --content-paths '/*'
